create table if not exists public.site_data (
  id integer primary key check (id = 1),
  settings jsonb not null default '{}'::jsonb,
  announcements jsonb not null default '[]'::jsonb,
  programs jsonb not null default '[]'::jsonb,
  news jsonb not null default '[]'::jsonb,
  documents jsonb not null default '[]'::jsonb,
  hero jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password_hash text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.site_data enable row level security;
alter table public.admin_users enable row level security;

-- The website server uses the Supabase service key. No public client access is needed.
revoke all on table public.site_data from anon, authenticated;
revoke all on table public.admin_users from anon, authenticated;

grant all on table public.site_data to service_role;
grant all on table public.admin_users to service_role;

insert into public.site_data (id) values (1) on conflict (id) do nothing;

-- Create the Storage bucket from the Dashboard or API as a public bucket named peace-files.
-- The server uploads/deletes files using the service key; public visitors only need read access.
